name: petrel_app_example
version: 1.0.0+1
publish_to: none
description: Petrel 热更新演示项目.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  get: 4.6.6
  flutter:
    sdk: flutter
  tdesign_flutter: ^0.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
